//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART8
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAPHANGTRUSO
    {
        public string SOPHIEUNHTS { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public Nullable<System.DateTime> HANSD { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual PHIEUNHAPHANGTRUSO PHIEUNHAPHANGTRUSO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
