//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART8
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
        }
    
        public string SOHD { get; set; }
        public Nullable<System.DateTime> NGAYBAN { get; set; }
        public string TONGTIEN { get; set; }
        public string TIENKHACHDUA { get; set; }
        public string TIENKHATRA { get; set; }
        public Nullable<int> TONGSL { get; set; }
        public string POS { get; set; }
        public string MATK { get; set; }
    
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
