//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART8
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public string MAKM { get; set; }
        public string MASP { get; set; }
        public Nullable<double> GIAKM { get; set; }
        public Nullable<System.DateTime> THOIGIANBD { get; set; }
        public Nullable<System.DateTime> THOIGIANKT { get; set; }
        public string NOIDUNG { get; set; }
        public string HINHANH { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
