//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDEXUAT
    {
        public PHIEUDEXUAT()
        {
            this.CTPHIEUDEXUATs = new HashSet<CTPHIEUDEXUAT>();
            this.PHIEUNHAPHANGTRUSOes = new HashSet<PHIEUNHAPHANGTRUSO>();
        }
    
        public string SOPHIEUDX { get; set; }
        public Nullable<System.DateTime> NGAYDEXUAT { get; set; }
        public string MANCC { get; set; }
        public string MATK { get; set; }
    
        public virtual ICollection<CTPHIEUDEXUAT> CTPHIEUDEXUATs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual ICollection<PHIEUNHAPHANGTRUSO> PHIEUNHAPHANGTRUSOes { get; set; }
    }
}
