//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPHANGCHINHANH
    {
        public PHIEUNHAPHANGCHINHANH()
        {
            this.CTPHIEUNHAPHANGCHINHANHs = new HashSet<CTPHIEUNHAPHANGCHINHANH>();
        }
    
        public string SOPHIEU { get; set; }
        public string SOPHIEUNHTS { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string CHINHANH { get; set; }
        public string MATK { get; set; }
    
        public virtual ICollection<CTPHIEUNHAPHANGCHINHANH> CTPHIEUNHAPHANGCHINHANHs { get; set; }
        public virtual PHIEUNHAPHANGTRUSO PHIEUNHAPHANGTRUSO { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
