//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPHANGTRUSO
    {
        public PHIEUNHAPHANGTRUSO()
        {
            this.CTPHIEUNHAPHANGTRUSOes = new HashSet<CTPHIEUNHAPHANGTRUSO>();
            this.PHIEUNHAPHANGCHINHANHs = new HashSet<PHIEUNHAPHANGCHINHANH>();
        }
    
        public string SOPHIEU { get; set; }
        public string SOPHIEUDX { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string MATK { get; set; }
    
        public virtual ICollection<CTPHIEUNHAPHANGTRUSO> CTPHIEUNHAPHANGTRUSOes { get; set; }
        public virtual PHIEUDEXUAT PHIEUDEXUAT { get; set; }
        public virtual ICollection<PHIEUNHAPHANGCHINHANH> PHIEUNHAPHANGCHINHANHs { get; set; }
    }
}
