//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
            this.CTPHIEUDEXUATs = new HashSet<CTPHIEUDEXUAT>();
            this.CTPHIEUNHAPHANGCHINHANHs = new HashSet<CTPHIEUNHAPHANGCHINHANH>();
            this.CTPHIEUNHAPHANGTRUSOes = new HashSet<CTPHIEUNHAPHANGTRUSO>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
            this.LICHSUGIAs = new HashSet<LICHSUGIA>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string HINHANH { get; set; }
        public string MALOAI { get; set; }
        public string MANCC { get; set; }
    
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        public virtual ICollection<CTPHIEUDEXUAT> CTPHIEUDEXUATs { get; set; }
        public virtual ICollection<CTPHIEUNHAPHANGCHINHANH> CTPHIEUNHAPHANGCHINHANHs { get; set; }
        public virtual ICollection<CTPHIEUNHAPHANGTRUSO> CTPHIEUNHAPHANGTRUSOes { get; set; }
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual ICollection<LICHSUGIA> LICHSUGIAs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
